ln -s ../../thirdparty/yamcs/yamcs-core/lib/guava-18.0.jar guava-18.0.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/hornetq-commons-2.4.6.Final.jar hornetq-commons-2.4.6.Final.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/hornetq-core-client-2.4.6.Final.jar hornetq-core-client-2.4.6.Final.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/hornetq-journal-2.4.6.Final.jar hornetq-journal-2.4.6.Final.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/hornetq-native-2.4.6.Final.jar hornetq-native-2.4.6.Final.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/hornetq-server-2.4.6.Final.jar hornetq-server-2.4.6.Final.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/jackson-core-2.4.4.jar jackson-core-2.4.4.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/janino-2.5.15.jar janino-2.5.15.jar
ln -s ../../thirdparty/yamcs/yamcs-web/target/dependency/*.jar *.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/javacsv-2.0.jar javacsv-2.0.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/jboss-logging-3.1.0.GA.jar jboss-logging-3.1.0.GA.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/jdatepicker-1.3.2.jar jdatepicker-1.3.2.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/jgroups-3.3.4.Final.jar jgroups-3.3.4.Final.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/jxl-2.6.10.jar jxl-2.6.10.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/log4j-1.2.14.jar log4j-1.2.14.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/netty-all-4.0.13.Final.jar netty-all-4.0.13.Final.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/protobuf-java-2.5.0.jar protobuf-java-2.5.0.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/protostuff-api-1.3.3.jar protostuff-api-1.3.3.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/protostuff-json-1.3.3.jar protostuff-json-1.3.3.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/rocksdbjni-3.10.1.jar rocksdbjni-3.10.1.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/slf4j-api-1.7.1.jar slf4j-api-1.7.1.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/slf4j-jdk14-1.7.1.jar slf4j-jdk14-1.7.1.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/snakeyaml-1.9.jar snakeyaml-1.9.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/tokyocabinet-1.18.jar tokyocabinet-1.18.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/yamcs-api-0.28.1.jar yamcs-api-0.28.1.jar
ln -s ../../thirdparty/yamcs/yamcs-core/target/yamcs-core-0.28.1.jar yamcs-core-0.28.1.jar
ln -s ../../thirdparty/yamcs/yamcs-simulation/target/yamcs-simulation-0.28.1.jar yamcs-simulation-0.28.1.jar
ln -s ../../thirdparty/yamcs/yamcs-web/target/yamcs-web-0.28.1.jar yamcs-web-0.28.1.jar
ln -s ../../thirdparty/yamcs/yamcs-core/lib/yamcs-xtce-0.28.1.jar yamcs-xtce-0.28.1.jar
